# Generated by Django 5.0.1 on 2024-01-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300, unique=True, verbose_name='نام کاربری')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('fname', models.CharField(max_length=300, verbose_name='نام')),
                ('lname', models.CharField(max_length=300, verbose_name='نام خانوادگی')),
                ('gender', models.BooleanField(max_length=530, verbose_name='جنسیت')),
                ('birth', models.DateTimeField(verbose_name='تاریخ تولد')),
                ('readadmin', models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین')),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'کاربران',
                'verbose_name_plural': 'لیست کاربران',
            },
        ),
    ]
