# Generated by Django 5.0.1 on 2024-01-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='members',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='members',
            name='readadmin',
        ),
    ]
