# Generated by Django 5.0.1 on 2024-01-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_product_productcategory_productinfo_producttag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='info',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pro_tag',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='ProductInfo',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
    ]
