# Generated by Django 5.0.1 on 2024-02-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0004_remove_product_category_remove_product_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('name', models.CharField(max_length=300, verbose_name='نام')),
                ('message', models.TextField(max_length=530, verbose_name='متن پیام')),
                ('date', models.DateTimeField(verbose_name='تاریخ نوشته')),
                ('seen', models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'لیست تماس با ما',
            },
        ),
    ]
