# Generated by Django 5.0.1 on 2024-01-26 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=300, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='رنگ')),
                ('texture', models.CharField(max_length=100, verbose_name='جنس و بافت')),
            ],
            options={
                'verbose_name': 'اطلاعات تکمیلی',
                'verbose_name_plural': 'لیست اطلاعات تکمیلی',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200, verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'تگ محصول',
                'verbose_name_plural': 'تگ محصولات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر محصول')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('description', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('availability', models.BooleanField(verbose_name='موجود/ناموجود')),
                ('count', models.IntegerField(verbose_name='تعداد محصول')),
                ('slug', models.SlugField(default='', unique=True, verbose_name='عنوان در url')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcategory', verbose_name='دسته بندی')),
                ('info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productinfo', verbose_name='اطلاعات')),
                ('pro_tag', models.ManyToManyField(to='products.producttag', verbose_name='تگ محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
