# Generated by Django 5.0.1 on 2024-01-26 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_pro_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ نوشته'),
            preserve_default=False,
        ),
    ]
