# Generated by Django 5.0.1 on 2024-01-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_pro_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='info',
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_pic',
            field=models.ImageField(blank=True, null=True, upload_to='products/static/products/media', verbose_name='تصویر محصول'),
        ),
    ]
