# Generated by Django 5.0.1 on 2024-01-31 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_product_info_alter_product_pro_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productinfo', verbose_name='اطلاعات'),
        ),
    ]
