# Generated by Django 5.0.1 on 2024-01-31 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='info',
        ),
    ]
