# Generated by Django 5.0.1 on 2024-01-31 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_product_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInfo',
        ),
    ]
