# Generated by Django 5.0.1 on 2024-01-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_delete_productinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='رنگ')),
                ('url_color', models.CharField(max_length=300, verbose_name='رنگ در url')),
            ],
            options={
                'verbose_name': 'رنگ محصول',
                'verbose_name_plural': 'لیست رنگ محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=100, verbose_name='استایل محصول')),
                ('url_style', models.CharField(max_length=300, verbose_name='استایل در url')),
            ],
            options={
                'verbose_name': 'استایل محصول',
                'verbose_name_plural': 'لیست استایل محصولات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='pro_color',
            field=models.ManyToManyField(to='products.productcolor', verbose_name='رنگ محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='pro_style',
            field=models.ManyToManyField(to='products.productstyle', verbose_name='استایل محصول'),
        ),
    ]
