# Generated by Django 5.0.1 on 2024-01-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_product_pro_color_alter_product_pro_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_color',
            field=models.ManyToManyField(to='products.productcolor', verbose_name='رنگ محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_style',
            field=models.ManyToManyField(to='products.productstyle', verbose_name='استایل محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_tag',
            field=models.ManyToManyField(to='products.producttag', verbose_name='تگ محصول'),
        ),
    ]
